<?php
?>

<table style="width:100%">
    <tr>
        <th>
            <h2 style="float: left;">Import Product Attribute</h2>
        </th>
        <!--    <th>-->
        <!--      <h2 style="float: left;">Configure Product Import Schedule</h2>-->
        <!--    </th>-->
    </tr>
    <tr>
        <td style="width: 50%">
            <div class="container">

                <form action="<?php echo $this->getUrl('import_attribute/index/save', ['_secure' => true]);?>" method="post" enctype="multipart/form-data">
                    <div class="row" style="margin-bottom: 20px">
                        <div class="col-25">
                            <label for="lname"><b>Attribute File</b></label> <a href="<?php echo $this->getUrl('import_attribute/index/sample', ['_secure' => true]);?>">Download Sample File</a>
                        </div>
                        <div class="col-75">
                            <input type="file" name="product_attribute" required>
                        </div>
                    </div>
                    <div class="row">
                        <input type="submit" value="Import Now">
                    </div>
                    <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey(); ?>" />
                </form>
                <p style="margin-top: 20px;"> Attribute Import Log ( <a href="<?=$this->getUrl('import_attribute/index/download', ['file' => 'attribute'])?>">View</a> / <a href="<?=$this->getUrl('import_attribute/index/delete', ['file' => 'attribute'])?>">Delete</a>)
            </div>
        </td>

        <!--    <td style="width: 50%">-->
        <!--      <div class="container">-->
        <!--          <a href="--><?php //= $block->getUrl('admin/system_config/edit/section/RCCsv/');?><!--" style="display: block;-->
        <!--    width: 115px;-->
        <!--    height: 46px;-->
        <!--    background: #4E9CAF;-->
        <!--    padding: 10px;-->
        <!--    text-align: center;-->
        <!--    border-radius: 5px;-->
        <!--    color: white;-->
        <!--    font-weight: bold;-->
        <!--    line-height: 25px;">Click Here</a>-->
        <!--      </div>-->
        <!--    </td>-->
    </tr>
</table>
